service: download-customer-csv

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${self:custom.secrets.NODE_ENV}
  region: us-east-1
  environment: 
    NODE_ENV: ${self:custom.secrets.NODE_ENV}

functions:
  saveToDynamo:
    handler: index.saveToDynamo
    events:
      - schedule: cron(0 1 * * ? *)

custom:
  secrets: ${file(secrets.json)}